plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.21'
    id 'dev.zacsweers.moshix' version '0.34.4'
//    id 'com.google.devtools.ksp' version "2.2.21-2.0.5"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
//    ksp 'com.squareup.moshi:moshi-kotlin-codegen:1.15.2'
    implementation 'com.squareup.moshi:moshi-kotlin:1.15.2'
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(17)
}
